In [ ]:
import numpy as np
import pandas as pd 

# set the random seed for reproducibility 
np.random.seed(123)  

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0, n_class_1

(900, 100)

In [ ]:
# create class 0
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

# create class 1
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [10]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [11]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [12]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Up-Sampling

In [13]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [ ]:
# this library is used to randomly up-sample or down-sample data, 
# for example to balance an imbalanced dataset.
from sklearn.utils import resample
df_minority_unsampled = resample(df_minority, replace=True, # sample will be added with replacement
         n_samples=len(df_majority), # unsamples minority with majority
         random_state=42
        )

In [18]:
df_minority_unsampled.shape

(900, 3)

In [19]:
df_minority_unsampled.head

<bound method NDFrame.head of      feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[900 rows x 3 columns]>

In [20]:
df_upsampled = pd.concat([df_minority, df_minority_unsampled])

In [22]:
df_upsampled['target'].value_counts()

target
1    1000
Name: count, dtype: int64

### Down-sampling

In [23]:
import numpy as np
import pandas as pd 

# set the random seed for reproducibility 
np.random.seed(123)  

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

# create class 0
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

# create class 1
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [24]:
# this library is used to randomly up-sample or down-sample data, 
# for example to balance an imbalanced dataset.
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, replace=False, # reduce the data points
         n_samples=len(df_minority), # unsamples majority with minority
         random_state=42
        )

In [25]:
df_majority_downsampled.shape

(100, 3)

In [26]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [27]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64