In [ ]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
# declaring the dataset
dataset =pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv')

In [ ]:
# reading the dataset
dataset.head()

                                                                  Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC DC  ISI BUI FWI              Classes
01  06    2012 29          57  18  0     65.7 3.4 7.6 1.3 3.4 0.5            not fire
02  06    2012 29          61  13  1.3   64.4 4.1 7.6 1   3.9 0.4            not fire
03  06    2012 26          82  22  13.1  47.1 2.5 7.1 0.3 2.7 0.1            not fire
04  06    2012 25          89  13  2.5   28.6 1.3 6.9 0   1.7 0              not fire

In [6]:
# getting the info
dataset.info

<bound method DataFrame.info of                                                                     Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC DC   ISI BUI  FWI              Classes
01  06    2012 29          57  18  0     65.7 3.4 7.6  1.3 3.4  0.5            not fire
02  06    2012 29          61  13  1.3   64.4 4.1 7.6  1   3.9  0.4            not fire
03  06    2012 26          82  22  13.1  47.1 2.5 7.1  0.3 2.7  0.1            not fire
04  06    2012 25          89  13  2.5   28.6 1.3 6.9  0   1.7  0              not fire
...                                                                                    ...
26  09    2012 30          65  14  0     85.4 16  44.5 4.5 16.9 6.5                fire
27  09    2012 28          87  15  4.4   41.1 6.5 8    0.1 6.2  0              not fire
28  09    2012 27          87  29  0.5   45.9 3.5 7.9  0.4 3.4  0.2            not fire
29  09    2012 24          54  18  0.1   79.7 4.3 15.2 1.7 5.1  0.7            not fire
30  09    2012 24          64  15  0.2   67.3 3.8 16.5 1.2 4.8  0.5           not fire

[247 rows x 1 columns]>

### Cleaning The Dataset

In [8]:
# missing values
dataset[dataset.isnull().any(axis = 1)]

                                                                                          Bejaia Region Dataset
Sidi-Bel Abbes Region Dataset NaN NaN  NaN NaN NaN NaN NaN  NaN  NaN    NaN  NaN  NaN                        NaN
14                            07  2012 37  37  18  0.2 88.9 12.9 14.6 9 12.5 10.4 fire                       NaN

In [14]:
dataset.loc[:, "Region"] = 0  # create column first
dataset.iloc[:122, dataset.columns.get_loc("Region")] = 0
dataset.iloc[122:, dataset.columns.get_loc("Region")] = 1
df = dataset

C:\Users\karan\AppData\Local\Temp\ipykernel_27472\3573850925.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  dataset.loc[:, "Region"] = 0  # create column first

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 247 entries, ('day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI') to ('30', '09', '2012', '24', '64', '15', '0.2', '67.3', '3.8', '16.5', '1.2', '4.8', '0.5')
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bejaia Region Dataset   245 non-null    object
 1   Region                  247 non-null    int64
dtypes: int64(1), object(1)
memory usage: 51.2+ KB

In [16]:
df[['Region']] = df[['Region']].astype(int)

In [17]:
df.head()

,,,,,,,,,,,,,Bejaia Region Dataset,Region
day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,0
01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0

In [18]:
df.isnull().sum()

Bejaia Region Dataset     2
Region                    0
dtype: int64

In [21]:
# removing the null values
df = df.dropna().reset_index(drop = True)
df.head()

  Bejaia Region Dataset   Region
0              Classes         0
1            not fire          0
2            not fire          0
3            not fire          0
4            not fire          0

In [22]:
df.iloc[[122]]

    Bejaia Region Dataset   Region
122            not fire          1

In [24]:
# remove the 122nd row
df = df.drop(122).reset_index(drop = True)

In [25]:
df.iloc[[122]]

    Bejaia Region Dataset   Region
122              Classes         1

In [26]:
df.columns

Index(['Bejaia Region Dataset ', 'Region'], dtype='object')

In [27]:
# fix spaces in column names
df.columns = columns.str.strip()
df.columns

NameError: name 'columns' is not defined